# Usa una imagen base de Python
FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo requirements.txt al contenedor
COPY requirements.txt .

# Instala las dependencias directamente en el contenedor
RUN pip install -r requirements.txt


# Copia el resto de los archivos de tu proyecto al contenedor
COPY . .

# Expón el puerto que Railway necesita (Railway lo mapeará al externo)
EXPOSE 8000

# Comando que se ejecutará al iniciar el contenedor
CMD ["/opt/venv/bin/python", "app.py"]
