# Usa una imagen base de Python
FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el contenido del proyecto al contenedor
COPY . .

# Instala las dependencias del archivo requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Expón el puerto que Railway necesita (Railway lo mapeará al externo)
EXPOSE 8000

# Comando que se ejecutará al iniciar el contenedor
CMD ["python", "app.py"]
